### ISSUE TITLE
Only scalar fields are supported in Theme Options

### ISSUE THREAD

**Issue by ojohnny** [matepaiva/wp-graphql-crb#12]
I tried getting a complex field from a theme option, but I get an error in Container.php line 176 that the callback expected 6 arguments but was passed 3.

Only the `getScalar` resolver seems to accept only three arguments, so I guess this is a bug?

**Comment by matepaiva** [comment]
I am really sorry I missed this issue. I will review your PR now and hopefully approve it. Thank you for the patience!

**Comment by matepaiva** [comment]
# New release! 

## Version 0.0.6
- Fix issue #13: a big thanks to @ojohnny for contributing to this open-source package. 👏🏼👏🏼👏🏼
