### ISSUE TITLE
Error: Type Crb_ThemeOptions must define one or more fields.

### ISSUE THREAD

**Issue by benada002** [matepaiva/wp-graphql-crb#8]
Hi,

If I try to run `GraphQL Code Generator`, I get the following error: `Type Crb_ThemeOptions must define one or more fields`.

I think one possible solution would be:

```diff
diff --git a/src/Container.php b/src/Container.php
index aaee152..284437e 100644
--- a/src/Container.php
+++ b/src/Container.php
@@ -21,6 +21,8 @@ class Container
 {
   private static $is_first_time = true;
 
+  private static $is_first_time_theme_options = true;
+
   public function __construct(CrbContainer $container)
   {
     $this->container = $container;
@@ -54,6 +56,12 @@ public function graphqlRegisterTypes()
       Container::$is_first_time = false;
       Container::registerStaticObjectTypes();
     }
+
+    if ($this->container->type === 'theme_options' && Container::$is_first_time_theme_options) {
+      Container::$is_first_time_theme_options = false;
+      Container::registerStaticThemeOptionObjectTypes();
+    }
+
     $this->registerFields();
   }
 
@@ -64,12 +72,14 @@ private function registerFields()
     }
   }
 
-  static function registerStaticObjectTypes()
+  static function registerStaticThemeOptionObjectTypes()
   {
-    register_graphql_object_type('Crb_ThemeOptions', [
-      'description' => \__("All the Carbon Field Theme Options", 'app'),
-      'fields' => [],
-    ]);
+    register_graphql_object_type(
+        'Crb_ThemeOptions', [
+        'description' => \__("All the Carbon Field Theme Options", 'app'),
+        'fields' => [],
+      ]
+    );
 
     register_graphql_field(
       'RootQuery',
@@ -81,7 +91,10 @@ static function registerStaticObjectTypes()
         }
       ]
     );
+  }
 
+  static function registerStaticObjectTypes()
+  {
     register_graphql_object_type('Crb_Select', [
       'description' => \__("The selected option/radio", 'app'),
       'fields' => [
```

Or do you've another idea?

**Comment by matepaiva** [comment]
Could you explain that solution? I don't understand how it fixes the issue 😕

**Comment by benada002** [comment]
Sorry, I guess, I wasn't clear enough. This error only occurs if I'm not making a `theme_options` container (`Container::make('theme_options')`). I think it's because the `registerStaticObjectTypes` function, as it now is, then results in an empty type.

To resolve that I took the `register_graphql_object_type` function (for `Crb_ThemeOptions`) and the `register_graphql_field` function (for `crb_ThemeOptions`) out of `registerStaticObjectTypes`, and stuck them into it's own `registerStaticThemeOptionObjectTypes` function. Then in the `graphqlRegisterTypes` function, I check if the current container is a `theme_options` container and only then (and the first time) I call the `registerStaticThemeOptionObjectTypes` to register the `Crb_ThemeOptions` type. Otherwise the (then empty) `Crb_ThemeOptions` type isn't registred. Which for me solves it.

**Comment by matepaiva** [comment]
Now I get it. I don't have the time to test it now, but I will accept it as you said you tested and it solved the issue for you.

**Comment by matepaiva** [comment]
New release: https://github.com/matepaiva/wp-graphql-crb/releases/tag/0.0.3

Thank you for the contribution!

**Comment by benada002** [comment]
Thanks. I updated and tried it again. Now I can run GraphQL Code Generator without problems.
